#!/bin/sh

SZD_PNAV="/var/packages/PHPNavigator"
DESKTOP="/usr/syno/synoman/webman/3rdparty/PHPNavigator"
PHPNavigatorTarget="${SZD_PNAV}/target"
PHPNavigatorUI="${PHPNavigatorTarget}/ui"
DSM_INDEX_ADD="/usr/syno/bin/pkgindexer_add"
DSM_INDEX_DEL="/usr/syno/bin/pkgindexer_del"

case "$1" in
	start)
		rm -f $DESKTOP
		if [ ! -z "$SYNOPKG_PKGNAME" -a -n "$SYNOPKG_DSM_VERSION_MAJOR" -a $SYNOPKG_DSM_VERSION_MAJOR -ge 4 ]; then
			ln -sf ${PHPNavigatorUI} ${DESKTOP}
			${DSM_INDEX_ADD} ${PHPNavigatorUI}/index.conf
		else
			ln -sf ${PHPNavigatorTarget}/desktop ${DESKTOP}
		fi
		;;
	stop)
		if [ -n "$SYNOPKG_DSM_VERSION_MAJOR" -a $SYNOPKG_DSM_VERSION_MAJOR -ge 4 ]; then 
			${DSM_INDEX_DEL} ${PHPNavigatorUI}/index.conf
		fi
		if [ ! -z "$SYNOPKG_PKGNAME" ]; then
			rm -f ${DESKTOP}
		fi
		;;
	status)
		if [ ! -f "${SZD_PNAV}/enabled" ]; then
			exit 1
		fi
		;;
	log)
		;;
	*)
		echo "Usage: $0 {start|stop|status|log}" >&2
		exit 1
		;;
esac

exit 0

